import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'theme.dart';
import 'screens/login_screen.dart';
import 'screens/main_layout.dart';

// IMPORTANT: Replace with the actual FirebaseOptions generated by flutterfire configure
// Since we are setting this up manually based on the web config, we will use the default initialization
// For Android/iOS, you MUST run `flutterfire configure` to generate firebase_options.dart.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    await Firebase.initializeApp(
      options: const FirebaseOptions(
        apiKey: "AIzaSyDekKQ9fK4G5DpSun9mGn40pJL0TyaU89w",
        authDomain: "asmapfe-9cc07.firebaseapp.com",
        projectId: "asmapfe-9cc07",
        storageBucket: "asmapfe-9cc07.firebasestorage.app",
        messagingSenderId: "276166068542",
        appId: "1:276166068542:web:a048690ecbbc4050c5046f",
        measurementId: "G-BVDF2MHP7K",
      ),
    );
  } catch (e) {
    print('Firebase initialization error: $e');
  }

  runApp(const SmartSecurityApp());
}

class SmartSecurityApp extends StatelessWidget {
  const SmartSecurityApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Security',
      theme: AppTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      home: const AuthWrapper(),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        
        if (snapshot.hasData) {
          return const MainLayout();
        }
        
        return const LoginScreen();
      },
    );
  }
}
